---
title: "STAT 184 Homework Exercises" 
subtitle: "DataComputing Chapter 17"
author: "Akash Anne"
editor_options: 
  markdown: 
    wrap: 72
---

# **Load Required Packages**

    library(dcData)
    library(tidyverse)

# DC Exercises Chapter 17

Problem 17.1.1: 
• Boys' names ending in a vowel

<!-- -->

    # load the data
    data("BabyNames")

    # top 10 boys' names ending in a vowel
    BabyNames %>%
      filter(sex == "M") %>%
      group_by(name) %>%
      summarise(total = sum(count)) %>%
      filter(grepl("[aeiou]$", name)) %>%
      arrange(desc(total)) %>%
      head(10)

    ## # A tibble: 10 x 2
    ##    name       total
    ##    <chr>      <int>
    ##  1 George   1451408
    ##  2 Joshua   1163815
    ##  3 Jose      539924
    ##  4 Kyle      469045
    ##  5 Lawrence  454323
    ##  6 Joe       448953
    ##  7 Willie    447403
    ##  8 Jesse     407183
    ##  9 Bruce     379233
    ## 10 Eugene    377338

Problem 17.1.3: 
• top 10 names ending with "joe" (like BettyJoe)

    # top 10 names ending with "joe" 

    # one interpretation: including the name "Joe" 
    BabyNames %>%
      filter(grepl("[Jj]oe$", name, ignore.case = TRUE)) %>%
      group_by(name) %>%
      summarise(total = sum(count)) %>%
      arrange(desc(total)) %>%
      head(10)

    ## # A tibble: 7 x 2
    ##   name       total
    ##   <chr>      <int>
    ## 1 Joe       460274
    ## 2 Billyjoe     393
    ## 3 Bobbyjoe      89
    ## 4 Marjoe        12
    ## 5 Billiejoe      6
    ## 6 Maryjoe        6
    ## 7 Johnnyjoe      5

    # another interpretation: not including the name "Joe" 
    BabyNames %>%
      filter(grepl(".joe$", name, ignore.case = TRUE)) %>%
      group_by(name) %>%
      summarise(total = sum(count)) %>%
      arrange(desc(total)) %>%
      head(10)

    ## # A tibble: 6 x 2
    ##   name      total
    ##   <chr>     <int>
    ## 1 Billyjoe    393
    ## 2 Bobbyjoe     89
    ## 3 Marjoe       12
    ## 4 Billiejoe     6
    ## 5 Maryjoe       6
    ## 6 Johnnyjoe     5

Problem 17.4.1 and 17.4.2

1. Strings matching the pattern will be 2 characters long

2. 61 different strings possible that can match like C[AOT] being 3

Problem 17.5.1: Names that have any of the words: "bar", "dam", "lory"

    # load the data
    BibleNames <- 
      readr::read_csv("https://mdbeckman.github.io/dcSupplement/data/BibleNames.csv")

    ## Rows: 2625 Columns: 2

    ## -- Column specification --------------------------------------------------------
    ## Delimiter: ","
    ## chr (2): name, meaning

    ## 
    ## i Use `spec()` to retrieve the full column specification for this data.
    ## i Specify the column types or set `show_col_types = FALSE` to quiet this message.

    # names that have "bar", "dam", or "lory"
    BibleNames %>%
      filter(grepl("bar|dam|lory", name, ignore.case = TRUE)) %>%
      group_by(name) %>%
      head(10)

    ## # A tibble: 10 x 2
    ## # Groups:   name [10]
    ##    name      meaning                   
    ##    <chr>     <chr>                     
    ##  1 Abarim    passages; passengers      
    ##  2 Aceldama  field of blood            
    ##  3 Adam      earthy; red               
    ##  4 Adamah    red earth; of blood       
    ##  5 Adami     my man; red; earthy; human
    ##  6 Barabbas  son of shame              
    ##  7 Barachel  that bows before God      
    ##  8 Barachias same as Barachel          
    ##  9 Barak     thunder                   
    ## 10 Barjesus  son of Jesus or Joshua

Problem 17.5.2: Names that end with "bar", "dam", or "lory"

    # names that end with "bar", "dam", or "lory"
    BibleNames %>%
      filter(grepl("bar$|dam$|lory$", name, ignore.case = TRUE)) %>%
      group_by(name) %>%
      head(10)

    ## # A tibble: 6 x 2
    ## # Groups:   name [6]
    ##   name    meaning           
    ##   <chr>   <chr>             
    ## 1 Adam    earthy; red       
    ## 2 Chebar  force or strength 
    ## 3 Elmodam the God of measure
    ## 4 Gazabar a treasurer       
    ## 5 Gibbar  strong            
    ## 6 Parbar  a suburb

\
